version: '3.5'

services:
  amber-cms:
    container_name: amber-cms
    build:
      context: amber-cms
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: amber-cmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./amber-cms/config:/opt/app/config
      - ./amber-cms/src:/opt/app/src
      - ./amber-cms/package.json:/opt/package.json
      - ./amber-cms/package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./amber-cms/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - amber-cms
    depends_on:
      - amber-cmsDB
      
  amber-cmsDB:
    container_name: amber-cmsDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - amber-cms-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - amber-cms
      
  amber-cmsAdminer:
    container_name: amber-cmsAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=amber-cmsDB
    networks:
      - amber-cms
    depends_on:
      - amber-cmsDB

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static-web-files:/usr/share/nginx/html
    networks:
      - amber-cms
    ports:
      - 80:80

      
  # app:
  #   container_name: amber-clinic-app
  #   build: 
  #     context: amber-clinic-app
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./amber-clinic-app:/app
  #     - /app/node_modules
  #     - static-web-files:/app/build
  #   networks:
  #   - amber-cms
volumes:
  amber-cms-data:
  static-web-files:

networks:
  amber-cms:
    name: Amber-cms
    driver: bridge
