import React from 'react';
import { useNavigate } from "@remix-run/react";
import { Button } from "@heroui/button";

const Kvkk = () => {
    const navigate = useNavigate();
    return (
        <div className="max-w-screen-lg mx-auto p-4">
            <h1 className="text-4xl text-amber-500 font-vollkorn mt-8 mb-2">6698 SAYILI KİŞİSEL VERİLERİN KORUNMASI KANUNU UYARINCA AYDINLATMA METNİ</h1>
            <p className="mb-4">Değerli Ziyaretçilerimiz</p>
            <p className="mb-4">Kişisel verileriniz, 6698 Sayılı Kişisel Verilerin Korunması Kanunu’nun 3’üncü maddesinde tanımlanan “veri sorumlusu” sıfatıyla DM Ağız Diş Sağlığı Hizmetleri Turizm Ticaret ve Sanayi Limited Şirketi (Özel Amber Ağız ve Diş Sağlığı Polikliniği – Clinic Amber) tarafından işlenmektedir.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">İşlenen Kişisel Veriler</h2>
            <p className="mb-4">DM Ağız Diş Sağlığı Hizmetleri Turizm Ticaret ve Sanayi Limited Şirketi’nde;</p>
            <p className="mb-4">(Özel Amber Ağız ve Diş Sağlığı Polikliniği – Clinic Amber)</p>
            <ul className="mb-4 list-disc list-inside">
                <li><strong className="text-amber-600"><span>Kimlik Bilgileriniz;</span></strong> adınız, soyadınız, TC kimlik numaranız, pasaport numaranız veya geçici TC kimlik numaranız, doğum tarihiniz, cinsiyetiniz, uyruğunuz,</li>
                <li><strong className="text-amber-600">İletişim Bilgileriniz;</strong> adresiniz, telefon numaranız, e-posta adresiniz, mesleğiniz, mektup veya sair vasıtalar aracılığı ile tarafımızla iletişime geçtiğinizde elde edilen kişisel verileriniz,</li>
                <li><strong className="text-amber-600">Muhasebesel Bilgileriniz;</strong> faturalama işlemi kapsamında talep etmeniz halinde ad, soy ad, adres, TC kimlik, vergi numarası, şahıs şirketi bilgileri (ödemeyi kredi kartı ile yapmanız halinde kart bilgileriniz kaydedilmeksizin ilgili bankaya aktarılmaktadır)</li>
                <li><strong className="text-amber-600">Görsel ve İşitsel verileriniz;</strong> açık rızanız dâhilinde hasta kayıt formuna eklenmek üzere fotoğrafınız, açık rızanız dâhilinde web sitemiz, sosyal medya hesaplarımız, tanıtım broşürleri veya tanıtıcı herhangi görsel veya basılı bir etkinlik formunda kullanılmak üzere görsel ve işitsel verileriniz, güvenlik kamerası tarafından alınan görsel ve işitsel verileriniz,</li>
                <li><strong className="text-amber-600">Tedaviye ilişkin veriniz;</strong> tedavi aşamaları, tedavi ücreti, zamanı, ödeme şekli, imza,</li>
                <li><strong className="text-amber-600">Sağlık verileriniz;</strong> kamu sağlığının korunması, koruyucu hekimlik, tıbbî teşhis, tedavi, bakım ve tedavi sonrası hizmetlerin yürütülmesi kapsamında röntgen sonuçlarınız, muayene verileriniz, randevu bilgileriniz, geçmiş veya devam eden hastalık ve alışkanlıklarınız dahil ancak bunlarla sınırlı olmaksızın tıbbî teşhis, tedavi ve bakım hizmetlerinin yürütülmesi sırasında veya bunların bir sonucu olarak elde edilebilecek sağlık veriniz,</li>
                <li>Açık rızanız dahilinde tarafınıza ileti gönderilmesi ve yapılan anketler kapsamında firmamız hakkında görüşleriniz kapsamında verileriniz işlenmektedir.</li>
            </ul>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">Kişisel Verileri İşleme Yöntemi, Amacı ve Hukuki Sebebi</h2>
            <p className="mb-4">Kişisel verileriniz, hasta kayıt formu, anamnez formu, proforma ve mutabakat formu, hasta bilgilendirme ve onam formu, sözleşme, e-posta, fatura, güvenlik kamerası gibi her türlü sözlü, yazılı, fiziki, görsel ya da elektronik yollarla ve cihazlarla, fiziki konumlarda görsel cihazlar ve fiziksel formlar ile toplanmaktadır.</p>
            <p className="mb-4">Kişisel verileriniz; kamu sağlığının korunması, koruyucu hekimlik, tıbbî teşhis, tedavi, bakım ve tedavi sonrası hizmetlerin yürütülmesi, muayene ve tedavi sırasında ve sonrasında yasal mevzuat gereği, doktorlarımız tarafından tedavi/muayene sonrası yapılacak işlemlerin kaydının tutulması açısından zorunluluk olması, şirketimizin meşru menfaatleri kapsamında kayıt tutma yükümlülüğünün bulunması, tedavi veya muayene sonrasında doktorlarımız tarafından kontrollerin yapılması, memnuniyet anketlerimizin yapılması ve tanıtım faaliyetleri, güvenliğin sağlanması, giriş çıkış kayıtlarının tutulması ve geçmişe yönelik olarak güvenlik kontrollerinin yapılması, sözleşmeden doğacak uyuşmazlıklarda mahkeme, icra dairesi, hakem heyeti gibi resmi kurum ve kuruluşlara karşı her türlü dava, cevap ve itiraz hakkının kullanılması, mevzuattan kaynaklanan yükümlülüklerin yerine getirilmesi, sizinle iletişime geçmek, bizimle iletişime geçtiğiniz takdirde sorun ve şikâyetlerinizi çözümlemek, randevu bilgilerinizi hatırlatmak amacıyla işlenmektedir.</p>
            <p className="mb-4">Kişisel verileriniz; kamu sağlığının korunması, koruyucu hekimlik, tıbbî teşhis, tedavi, bakım ve tedavi sonrası hizmetlerin yürütülmesi, sözleşmenin kurulması ve ifası için veri işlemenin gerekli olması, hukuki yükümlülüğün yerine getirilmesi, hakların tesisi, kullanılması veya korunması için veri işlemenin ve aktarmanın zorunlu olması, veri sorumlusunun meşru menfaatleri için veri işlenmesinin zorunlu olması, kanunlarda açıkça yazılı olması ve açık rızanıza dayalı hukuki sebeplerle işlenmektedir.</p>
            <p className="mb-4">İşlenen bu verileriniz yasal süreleri boyunca yurt içinde bulunan DM Ağız Diş Sağlığı Hizmetleri Turizm Tic. Ve San. Ltd. Şti. (Özel Amber Ağız ve Diş Sağlığı Polikliniği – Clinic Amber) sunucularında saklanacak, yasal sürelerin dolmasını takiben kanuna uygun olarak hazırlanan kişisel veri imha politikası kapsamında imha edilecektir.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">Kişisel Verilerin Aktarılması</h2>
            <p className="mb-4">İşbu işlenen verileriniz şirketimiz tarafından herhangi bir üçüncü kişi ile paylaşılmamaktadır. Ancak şirket binası içerisinde bir adli vakıa gerçekleşmesi veya bir hakkın kullanımı sebebiyle yasal mercilere sunulmasının zorunlu olması halinde işbu veriler kanunun 5’inci maddesinin 2’nci fıkrası uyarınca ayrıca rızanıza gerek olmaksızın yasal merciler ve avukatlarımız ile paylaşılabilecektir. Ayrıca bilişim teknolojileri ya da uzmanlık gerektiren danışmanlık vb. hizmetleri almak, kişisel veri toplama süreçlerinde ürün ve hizmet desteği almak gibi amaçlarla yurtiçinde bulunan iş ortakları ve hizmet sağlayıcılarıyla, tedavi sonrası sürecin takibi bakımından gerektiğinde şirketin diğer şubelerindeki çalışan ve danışmanlarımızla, kullandığımız ürünlere ilişkin hizmetlerde bulunan tedarikçilerimiz, iş ortaklarımız ile ve kredi kartı ile ödeme yapmanız halinde kart bilgileriniz kaydedilmeksizin ilgili banka ile paylaşılabilecektir.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">İletişim</h2>
            <p className="mb-4">6698 Sayılı Kişisel Verileri Koruma Kanunu’nun 11’inci maddesinde sayılan kişisel verilerinizin işlenip işlenmediğini öğrenme, kişisel verileriniz işlenmişse buna ilişkin bilgi talep etme, kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme, yurtiçinde veya yurtdışında kişisel verilerinizin aktarıldığı üçüncü kişileri bilme, kişisel verilerinizin eksik veya yanlış işlenmiş olması halinde bunların düzeltilmesini isteme, KVKK mevzuatında öngörülen şartlar çerçevesinde kişisel verilerinizin silinmesini veya yok edilmesini isteme, kişisel verilerinizin aktarıldığı üçüncü kişilere bildirilmesini isteme, işlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle aleyhinize bir sonucun ortaya çıkmasına itiraz etme, kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğramanız halinde bu zararın giderilmesini talep etme haklarına sahipsiniz. Bu madde kapsamında şirketimize başvuruda bulunabileceğinizi hatırlatırız. Yapacağınız başvurularınızı, şirketin söz konusu başvuru prosedürü için tahsis edilmiş olan <a href="mailto:clinicamber.kvkk@gmail.com" className="text-blue-500">clinicamber.kvkk@gmail.com</a> e-posta adresine veya şirketin “Orhangazi Mah. Alparslan Türkeş Cad. No:2/A Pendik/İstanbul” adresine yazılı olarak iletebilirsiniz.</p>
            <h1 className="text-4xl text-amber-500 font-vollkorn mt-8 mb-2">Çerez Politikası</h1>
            <p className="mb-4">Biz, Clinic Amber, olarak güvenliğinize önem veriyor ve bu Çerez Politikası ile siz sevgili ziyaretçilerimizi, web sitemizde hangi çerezleri, hangi amaçla kullandığımız ve çerez ayarlarınızı nasıl değiştireceğiniz konularında kısaca bilgilendirmeyi hedefliyoruz.</p>
            <p className="mb-4">Sizlere daha iyi hizmet verebilmek adına, çerezler vasıtasıyla, ne tür kişisel verilerinizin hangi amaçla toplandığı ve nasıl işlendiği konularında, kısaca bilgi sahibi olmak için lütfen bu Çerez Politikasını okuyunuz. Daha fazla bilgi için Gizlilik Politikamıza göz atabilir ya da bizlerle çekinmeden iletişime geçebilirsiniz.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">Çerez Nedir?</h2>
            <p className="mb-4">Çerezler, kullanıcıların web sitelerini daha verimli bir şekilde kullanabilmeleri adına, cihazlarına kaydedilen küçük dosyacıklardır. Çerezler vasıtasıyla kullanıcıların bilgilerinin işleniyor olması sebebiyle, 6698 sayılı Kişisel Verilerin Korunması Kanunu gereğince, kullanıcıların bilgilendirilmeleri ve onaylarının alınması gerekmektedir.</p>
            <p className="mb-4">Bizler de siz sevgili ziyaretçilerimizin, web sitemizden en verimli şekilde yararlanabilmelerini ve siz sevgili ziyaretçilerimizin kullanıcı deneyimlerinin geliştirilebilmesini sağlamak adına, çeşitli çerezler kullanmaktayız.</p>
            <h3 className="text-2xl text-amber-500 font-vollkorn mt-8 mb-2">1. Zorunlu Çerezler</h3>
            <p className="mb-4">Zorunlu çerezler, web sitesine ilişkin temel işlevleri etkinleştirerek web sitesinin kullanılabilir hale gelmesini sağlayan çerezlerdir. Web sitesi bu çerezler olmadan düzgün çalışmaz.</p>
            <h3 className="text-2xl text-amber-500 font-vollkorn mt-8 mb-2">2. Performans Çerezleri</h3>
            <p className="mb-4">Performans çerezleri, ziyaretçilerin web sitesine ilişkin kullanım bilgilerini ve tercihlerini anonim olarak toplayan ve bu sayede web sitesinin performansının geliştirilmesine olanak sağlayan çerezlerdir.</p>
            <h3 className="text-2xl text-amber-500 font-vollkorn mt-8 mb-2">3. Fonksiyonel Çerezler</h3>
            <p className="mb-4">Fonksiyonel çerezler, kullanıcıların web sitesine ilişkin geçmiş kullanımlarından yola çıkılarak gelecekteki ziyaretlerinde tanınmalarını ve hatırlanmalarını sağlayan ve bu sayede web sitelerinin kullanıcılara dil, bölge vb. gibi kişiselleştirilmiş bir hizmet sunmasına olanak tanıyan çerezlerdir.</p>
            <h3 className="text-2xl text-amber-500 font-vollkorn mt-8 mb-2">4. Reklam Çerezleri</h3>
            <p className="mb-4">Reklam çerezleri, üçüncü taraflara ait çerezlerdir ve web sitelerinde ziyaretçilerin davranışlarını izlemek için kullanılırlar. Bu çerezlerin amaçları, ziyaretçilerin ihtiyaçlarına yönelik ilgilerini çekecek reklamların gösterilmesine yardımcı olmaktır ve sorumluluğu çerez sahibi üçüncü taraflara aittir.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">Çerezler İle İşlenen Kişisel Veriler Nelerdir?</h2>
            <p className="mb-4">Kimlik (isim, soy isim, doğum tarihi vb.) ve iletişim (adres, e-posta adresi, telefon, IP, konum vb.) bilgileriniz tarafımızca, çerezler (cookies) vasıtasıyla, otomatik veya otomatik olmayan yöntemlerle ve bazen de analitik sağlayıcılar, reklam ağları, arama bilgi sağlayıcıları, teknoloji sağlayıcıları gibi üçüncü taraflardan elde edilerek, kaydedilerek, depolanarak ve güncellenerek, aramızdaki hizmet ve sözleşme ilişkisi çerçevesinde ve süresince, meşru menfaat işleme şartına dayanılarak işlenecektir.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">Çerezler Hangi Amaçla Kullanılmaktadır?</h2>
            <p className="mb-4">Web sitemizde, şüpheli eylemlerin tespiti yoluyla güvenliğin sağlanması, kullanıcıların tercihleri doğrultusunda işlevsellik ve performansın artırılması, ürünlerin ve hizmetlerin geliştirilmesi ve kişiselleştirilmesi ile bu hizmetlere ulaşımın kolaylaştırılması, sözleşmesel ve hukuki sorumlulukların yerine getirilmesi amaçlı çerezler kullanmaktadır. Ayrıca kullanıcıların daha geniş kapsamlı hizmet sağlayıcılar ile buluşturulabilmesi amacıyla reklam çerezleri ve üçüncü taraflarla bilgi paylaşımı da söz konusudur.</p>
            <h2 className="text-3xl text-amber-500 font-vollkorn mt-8 mb-2">Çerezler Nasıl Yönetilmektedir?</h2>
            <p className="mb-4">Tüm bu açıklamalardan sonra, hangi çerezlerin kullanılacağı konusu, tamamen kullanıcılarımızın özgür iradelerine bırakılmıştır. Çerez tercihlerinizi, tarayıcınızın ayarlarından silerek ya da engelleyerek, web sitemize adım attığınız anda yönetebilir ya da gelecekte, istediğiniz zaman bu ayarları değiştirebilirsiniz. Daha ayrıntılı bilgi için Gizlilik Politikamıza göz atabilir ya da bizlerle <a href="mailto:info@clinicamber.com" className="text-blue-500">info@clinicamber.com</a> e-mail adresi üzerinden iletişime geçebilirsiniz.</p>
            <p className="mb-4">DM Ağız Diş Sağlığı Hizmetleri</p>
            <p className="mb-4">Turizm Ticaret Ve Sanayi Limited Şirketi</p>
            <p className="mb-4">(Özel Amber Ağız ve Diş Sağlığı Polikliniği – Clinic Amber)</p>
                <Button className="bg-amber-500 text-white" onClick={() => navigate("/") }>{"<- Anasayfaya dön"}</Button>
        </div>
    );
};

export default Kvkk;



